export const ACTUALITES = 'Actualites';
export const CHAT = 'Chat';
export const COINS = 'Coins';
export const HOME = 'Home';
export const HOTSPOT = 'Hotspot';
export const LAMDA_MONEY = 'Lamda money';
export const MISSIONS = 'Missions';
export const NOTIFICATIONS = 'Notifications';
export const SIGN_UP1 = 'SignUp1';
export const SIGN_UP2 = 'SignUp2';
export const ACTIVE_ACCOUNT = 'ACTIVE_ACCOUNT';
export const SPLASHSCREEN = 'SplashScreen';
export const START = 'Start';
export const AUTH = 'Auth';
export const HOMESTACK = "HOMESTACK";
export const DETAIL_FEED = "Detail_feed";
export const SIGN_IN = "SignIn";
export const DISCUSSION = "Discussion";
export const PROFIL_ENTERPRISE = "ProfilEnterprise"
export const LAMDA_STORE = "LamdaStore"
export const PROFIL = "Profil"
export const DRAWER = "Drawer"

export const HOMESTART = 'Home_start';
export const COINSTART = 'Coin_start';
export const NOTIFICATIONSTART = 'Notification_start';